[package]
name = "ipc-userd"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.205", features = ["derive"] }
ipc-macro = { path = "../../ipc-macro" }
ipc = { path = "../../ipc" }
